### ISSUE TITLE
I’ve released a markdown documentation generator

### ISSUE THREAD

**Issue by rob-blackbourn** [rr-/docstring_parser#16]
Hi,

I’ve released a markdown documentation package using this project: [jetblack-markdown](https://github.com/rob-blackbourn/jetblack-markdown).

The documentation it generates can be found [here](https://rob-blackbourn.github.io/jetblack-markdown/). The [API](https://rob-blackbourn.github.io/jetblack-markdown/api/jetblack_metadata/) section is where the generated code is. 

I’ve been using google docstrings. I would expect it to work for “rest”, but I haven’t tried it. 

Rob

**Comment by rr-** [comment]
Thanks for letting us know but I'm not sure what you expect us to do here?

**Comment by rob-blackbourn** [comment]
Sorry. Not really an issue! Just thought it might be interesting/useful.
