### ISSUE TITLE
Promotion

### ISSUE THREAD

**Issue by jpic** [rr-/docstring_parser#22]
Hi all,

Thank you for this very, very nice package.

Would you be interested in adding a section about open source projects using this package in the README or somewhere ? I feel this could help look more "production ready" as-in "is in production in the following: ". Not necessary, but could be nice.

Otherwise please discard this message and close this issue

Have a great day and keep up the gr8 work !

**Comment by rr-** [comment]
Thanks for reaching out. That's always appreciated. I don't promise I'll immediately add it as I'd like to have a few more examples before creating such section.

**Comment by EpicWink** [comment]
It's a good use-case for the wiki feature in GitHub

**Comment by rr-** [comment]
Closing
