### ISSUE TITLE
make a conda-forge package

### ISSUE THREAD

**Issue by Chilipp** [rr-/docstring_parser#23]
Hey! Thanks for this wonderful package! 

Are there any plans to make this package available via the [conda-forge](https://conda-forge.org) anaconda channel?

I am the developer of [docrep](http://docrep.readthedocs.io/), a package that reads docstrings and let's the developer using it in another place. Currently I am using my own regex-based interpretation algorithms (and they only work for numpydoc-style docstrings), but I'd very much like to use `docstring_parser` instead.

In case there is interest, I'd be happy to draft a PR for the [staged-recipes](https://github.com/conda-forge/staged-recipes) repository.

**Comment by rr-** [comment]
Sorry I don't know what's anaconda and as such I don't have any plans to release it there, thus I welcome anyone who is willing to maintain a package there to go for it.

**Comment by Chilipp** [comment]
Hey @rr-! I strongly recommend anaconda. Particularly for Python it has a lot of very convenient functionalities and makes the installation of c, c++ and FORTRAN-based packages much more convenient on all platforms (see this blog post for instance: https://www.anaconda.com/blog/understanding-conda-and-pip). The conda-forge channel is community-driven platform with the basic idea that the maintainers of the packages make their packages available via conda. The overhead of maintaining a package like `docstring_parser` is very low. Each package in this channel get's a dedicated github repository (see [this one for docrep](https://github.com/conda-forge/docrep-feedstock), for instance). Everytime a new release is made on pypi, a bot will create a PR to also update the package on the conda-forge channel (see [here](https://github.com/conda-forge/docrep-feedstock/pull/9) for instance) and, once it is merged, it makes the package available via `conda install -c conda-forge docstring_parser`

Anyway, for a package like `docstring_parser` it of course does not make many advantages, as the installation via `pip` is straight-forward, but for more complex packages that might depend on `docstring_parser` in the future, conda gives a great benefit and therefore it would be good to have it available there, too.

Are you ok if I add you there as a maintainer? I can take care of it, if you like (it's [anyway not much work](https://conda-forge.org/docs/maintainer/adding_pkgs.html#maintainer-role)), but as the creator of this package, you should have access to the Github repository, too.

**Comment by rr-** [comment]
>Are you ok if I add you there as a maintainer? I can take care of it, if you like (it's anyway not much work), but as the creator of this package, you should have access to the Github repository, too.

I'm OK with this, and thanks for offering to create the initial work for this :)

**Comment by rr-** [comment]
@Chilipp I think the package is working upstream, right? If so, is it OK to close this issue?

**Comment by Chilipp** [comment]
Yes, sorry. I forgot
