### ISSUE TITLE
In ReST, default value is not found if description is multiline

### ISSUE THREAD

**Issue by HtheChemist** [rr-/docstring_parser#24]
re.match(r'.*defaults to (.+)', desc) will not find "defaults to" if there is a \n in the line. Changing this to re.match(r'.*defaults to (.+)', desc, flags=re.DOTALL) will allow to find "defaults to" even if there is a \n in the description.

**Comment by rr-** [comment]
Thanks, released as 0.7.2. LMK if it works for you.
