### ISSUE TITLE
Parameter description parsing captures less indented text of another section

### ISSUE THREAD

**Issue by Ark-kun** [rr-/docstring_parser#29]
Expected behavior: Parameter description ends when there parser encounters less indented line.

Actual behavior: The parameter description capturing does not seem to stop when less indented line is encountered and captures it as well.

```python
def foo():
    '''Converts Keras HDF5 model to Tensorflow SavedModel format.

    Args:
        model_path: Keras model in HDF5 format.
        converted_model_path: Keras model in Tensorflow SavedModel format.

    Annotations:
        author: Alexey Volkov <alexey.volkov@ark-kun.com>
    '''
```

The description for `converted_model_path` becomes:
```
Keras model in Tensorflow SavedModel format.
Annotations:
```

P.S. It would be really great if it was possible to parse additional sections that are not currently recognized by the docstring_parser.

**Comment by rr-** [comment]
Unfortunately I don't have capacity to work on open source atm, so a pull request is encouraged.

I agree about unknown sections.
