### ISSUE TITLE
Question: does it raise for invalid docstrings?

### ISSUE THREAD

**Issue by julien-c** [rr-/docstring_parser#35]
Hi, 

Thanks for your library it looks awesome. Does the parser raise an exception if the docstring's syntax is not correct Google-style syntax?

(Trying to build a simple docstring CI validation in my repo)

Thanks!

**Comment by Peter200lx** [comment]
Looks like this issue is hitting https://github.com/timothycrosley/pdocs/pull/19 as well, ideally a misparse should be caught and raised as a `docstring_parser.ParseError` instead of the `ValueError` getting propagated up to the calling tool

**Comment by rr-** [comment]
Sorry for the late reply. It's supposed to raise a ParseError, if it does not, it's an error and we need specific input to debug it.

**Comment by Peter200lx** [comment]
Here is a poorly formatted do string that would hit this:
```python
def test(param: str) -> str:
    """This is a test

    Args:
        param - poorly formatted
    """
    return param

```

**Comment by rr-** [comment]
Thanks @Peter200lx , I can confirm that 0.8 still had problem with this kind of input and the package now raises a ParseError as of 0.8.1.
