### ISSUE TITLE
Installation behind proxy not possible

### ISSUE THREAD

**Issue by DavidTorresOcana** [rr-/docstring_parser#41]
### Environment:
* Windows 10
* Python 3.7
* Machine on network behind proxy

### Problem:
Trying to install package behind proxy
`python -m pip install --proxy="http://username:passw@proxy_ip:port" --user docstring_parser`
### Yields:
```
Collecting docstring_parser
  Downloading https://files.pythonhosted.org/packages/b0/d9/fff7bdbc6bcd949dbf8bd64967a07d79f2767ae147fc5c1f0b2c8a063a77/docstring_parser-0.8.1.tar.gz
  Installing build dependencies ... error
  Complete output from command "C:\Program Files\Python37\python.exe" "C:\Program Files\Python37\lib\site-packages\pip" install --ignore-installed --no-user --prefix C:\Users\dto2028\AppData\Local\Temp\pip-build-env-uhegqdhr\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.8.0 wheel:
  Collecting setuptools>=40.8.0
    Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/setuptools/
    Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))': /simple/setuptools/
.....
```

### Possible reasons:
* Installation request re-installation of _setuptools_ and _wheel_ packages with `--ignore-installed` and striping out the proxy flag, hence causing installation to fail

**Comment by rr-** [comment]
That looks like a problem with your infrastructure, not this package.

**Comment by rr-** [comment]
Since `wheel` isn't mentioned anywhere in our repository at all I assume this is not our bug.

**Comment by DavidTorresOcana** [comment]
After checking with proxy, this problem is indeed caused by how the package is installed, possibly due to reason stated above.

As shared, package download gets through proxy without problem, just other ones (_setuptools_ and _wheel_) do not.

This issue should be reopened.

**Comment by rr-** [comment]
I am not sure how the problems with downloading quite basic packages that are not part of this project, through a server that is not a part of this project's infrastructure, have to do with this project.

>python -m pip install --proxy="http://username:passw@proxy_ip:port" --user setuptools

Try this.

**Comment by DavidTorresOcana** [comment]
> python -m pip install --proxy="http://username:passw@proxy_ip:port" --user setuptools

works and installs without problem. Even after removing and installing it again.

Trying after that:
> python -m pip install --proxy="http://username:passw@proxy_ip:port" --user docstring_parser

Yields same result:
```
Collecting docstring_parser
  Downloading docstring_parser-0.11.tar.gz (22 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Program Files\Python37\python.exe' 'C:\Users\username\AppData\Local\Temp\pip-standalone-pip-dna7knfa\__env_pip__.zip\pip' install --ignore-installed --no-user --prefix 'C:\Users\username\AppData\Local\Temp\pip-build-env-872tn9lz\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple --trusted-host pypi.org --trusted-host files.pythonhosted.org -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (9 lines):
```
