### ISSUE TITLE
raise ParseError(f'Can\'t infer indent from "{chunk}"')

### ISSUE THREAD

**Issue by yalvhe2009** [rr-/docstring_parser#6]
I uesed this module on win10 platform.when I call ` from docstring_parser import parse`, It reported that:

`raise ParseError(f'Can\'t infer indent from "{chunk}"')`

how can I slove this problom?

thank you.

**Comment by rr-** [comment]
This is very bogus, but you're most probably trying to run parser on docstrings that do not follow either rest or google formatting, thus the error is valid. If you think there is a bug, please send specific docstring that causes the problem and the expected result.
