### ISSUE TITLE
PyPI tarball lacks license

### ISSUE THREAD

**Issue by lachs0r** [rr-/docstring_parser#7]
Please include the license file in your PyPI distribution to make it redistributable.

**Comment by rr-** [comment]
@lachs0r please elaborate on the motivation of these tickets?

**Comment by lachs0r** [comment]
> @lachs0r please elaborate on the motivation of these tickets?

The licenses you use contain paragraphs like this one:
> The above copyright notice and this permission notice shall be included in 
> all copies or substantial portions of the Software.

Thus, a distribution packaging your module would be in violation of its 
license if it did not include a copy of it with the software. At least some 
Linux distributions also have legal teams that would take issue with this and 
reject packages because of this.

**Comment by rr-** [comment]
Released as 0.4, thanks
