### ISSUE TITLE
Add published package installation to README

### ISSUE THREAD

**Issue by jspaezp** [rr-/docstring_parser#73]
Hey there!

This project looks amazing, I am very excited to try it out.
I was wondering what you thought about adding to the readme the basic installation instructions from the releases?

maybe something as ...  installation: `pip install docstring_parser` to make clear it is pypi-published.
Maybe also reference the conda forge package?

@Chilipp How is that done? im not a conda user ...

Thanks a lot!
LMK if you want me to make it a super simple PR

**Comment by rr-** [comment]
Sure, let's add it. LMK once you create a PR.

**Comment by Chilipp** [comment]
hey @jspaezp! Installation via conda requires two steps:

1. download and install [miniconda](https://conda.io/en/latest/miniconda.html) or [anaconda](https://docs.anaconda.com/anaconda/install/)
2. install the package from the `conda-forge` channel via `conda install -c conda-forge docstring_parser` or create a new conda environment via `conda create -n my-new-environment -c conda-forge docstring_parser`

**Comment by jspaezp** [comment]
Thanks a lot for the reply!

Made a PR https://github.com/rr-/docstring_parser/pull/74

**Comment by rr-** [comment]
The PR was merged.
