### ISSUE TITLE
Fails to parse google style when ",optional" in docstring.

### ISSUE THREAD

**Issue by rob-blackbourn** [rr-/docstring_parser#8]
Hi,

Great project!

The following docstring fails to find the type for arg4 and arg5:

```python
    text = """A mock function

    A function to use in tests

    Args:
        arg1 (str): The first arg
        arg2 (List[int]): The second arg
        arg3 (datetime): The third arg
        arg4 (Optional[Decimal], optional): The fourth arg. Defaults to Decimal('1').
        arg5 (Optional[float], optional): The fifth arg. Defaults to None.

    Raises:
        ValueError: It doesn't actually raise this error

    Returns:
        Dict[str, Any]: The args as a dictionary
    """
```

This can be fixed by changing line 102 of google.py from
```python
        m = re.match(r"(\S+) \((\S+)\)$", before)
```

to
```python
        m = re.match(r"\s*(.+?)\s*\(\s*(.*[^\s]+)\s*\)", before)
```

Rob

**Comment by rr-** [comment]
Hi, could you link to example where this kind of documentation is used?

**Comment by rob-blackbourn** [comment]
I agree it's weird.

The example I gave was autogenerated by the [VSCode autoDocstring](https://marketplace.visualstudio.com/items?itemName=njpwerner.autodocstring) extension. The ",optional" appears whenever the default argument "= None" is applied.

I can't find a formal grammar for Google docstring, but the sphinx napoleon docstring extension has some examples [here](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html). This is where a stole the regex :-O

I'm not sure how it should be parsed. My current problem is that the argument name can't be identified (it returns "arg4 (Optional[Decimal], optional)"), so I miss the description. One possibility would be to add another property to the DocstringParam class `is_optional', but you would want this to be consistent with other docstring formats, which might not be possible.

**Comment by rr-** [comment]
Added basic support for `, optional` on master as well as a couple of changes inspired by yours, lmk if it works for you

**Comment by rob-blackbourn** [comment]
Perfect!

Can you publish to pypi?

**Comment by rr-** [comment]
Released as 0.5

**Comment by rob-blackbourn** [comment]
Thank you :)

**Comment by rob-blackbourn** [comment]
FYI I'm using docstring-parser for a [REST framework](https://github.com/rob-blackbourn/bareASGI-rest). Just done my first pre-release version.
